apiVersion: v1
kind: Service
metadata:
  name: daycare-app-service
  namespace: apps
spec:
  selector:
    app: daycare-app  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000