apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-monitor
  namespace: monitoring

  # 🔴 VERY IMPORTANT (must match your Helm release name)
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: webapp   # 👈 must match your Service label

  namespaceSelector:
    matchNames:
      - apps        # 👈 where your app is deployed

  endpoints:
    - port: http   # 👈 must match Service port name
      path: /metrics
      interval: 15s