apiVersion: v1
kind: Service
metadata:
  name: fashion-store-service
  namespace: apps
spec:
  selector:
    app: fashion-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80