apiVersion: v1
kind: Service
metadata:
  name: daycare-app-service
  namespace: apps
  labels:
    app: daycare-app   # ✅ ADD THIS
spec:
  selector:
    app: daycare-app
  ports:
    - name: http       # ✅ ADD THIS
      protocol: TCP
      port: 80
      targetPort: 5000